### ISSUE TITLE
Typescript support for Bluetooth?

### ISSUE THREAD

**Issue by georgeedwards** [EddyVerbruggen/nativescript-bluetooth-demo#11]
Could we support Typescript functionality for using Bluetooth. I think this would most likely just mean creating some definition files for a Peripheral, Service and Characteristic. 

Given the difficulty in testing ble functionality with unit tests and Continuous integration, this added type checking would make it easier to avoid bugs.

**Comment by EddyVerbruggen** [comment]
Do you mean like [this](https://github.com/EddyVerbruggen/nativescript-bluetooth/blob/master/bluetooth.d.ts)?

**Comment by georgeedwards** [comment]
Oh Amazing! Thanks, maybe a note about that in the readme would be helpful? (apologies if I missed it and there was one).

**Comment by kartonki** [comment]
Hi Eddy!
I just noticed that latest release 1.1.2 is not having the update done to the bluetooth.d.ts filehttps://github.com/EddyVerbruggen/nativescript-bluetooth/commit/7de9e755879055f8ff628accd644a507cc0b2a2a
Do you plan to push a new release to NPM ?I know this is small, and there is a PR from georgeedwards possibly under review
ThanksJorge

Date: Sat, 28 May 2016 04:58:14 -0700
