### ISSUE TITLE
Scan does not find any device on Android 6.0

### ISSUE THREAD

**Issue by jmartsch** [EddyVerbruggen/nativescript-bluetooth-demo#13]
I cloned and compiled the App on windows for Android and installed it on my phone (LG G4 with Android 6.0). When I push the "Is Bluetooth enabled" Button it says "Yes".
If I click on the button "Any peripheral" nothing happens.
I have to Eddystone URL beacons here that can be seen in other BLE scanning apps.
Any suggestions?

**Comment by jiwonyune** [comment]
I have the same problem, and I am using Android 6, too.

**Comment by EddyVerbruggen** [comment]
Sounds a bit similar to [this](https://github.com/EddyVerbruggen/nativescript-bluetooth/issues/5).. can you check if that makes a difference?

**Comment by jiwonyune** [comment]
I enabled the location service, but it doesn't seem to work for me.

**Comment by F481** [comment]
Same as for @jmartsch , tested it with location service on/off.
- Has the other device to be support BLE too or should any bluetooth device get showed in the list?
- I tried to simulate the BLE Peripheral with this app: https://play.google.com/store/apps/details?id=io.github.webbluetoothcg.bletestperipheral&hl=en (but no success)
I tested with a Nexus 4 (Android 5.1.1) and a HTC One M8 (Android 6.0)

**Comment by basilinjoe** [comment]
It's not working for Android 5.0  either

**Comment by tomaszciejka** [comment]
It doesn't work on 7.1.1 either. Any suggestions where can we take a look? (doesn't not find any devices)

It's strange because using https://github.com/sebawita/nativescript-mip-simple-ng app (which is based on you library) it finds the other devices.

**Comment by abinaj** [comment]
It doesn't work on 7.1.2 either. Any idea, how to solve this issue please?
