### ISSUE TITLE
Cannot run this on a iPhone 6s iOS 10

### ISSUE THREAD

**Issue by dotdreaming** [EddyVerbruggen/nativescript-bluetooth-demo#14]
I can build and run the demo app on a simulator, but when I come to running the app on an iPhone connected device it keeps crashing. 
****\* Fatal JavaScript exception - application has been terminated. *****

Does it work with iOS 10?

**Comment by EddyVerbruggen** [comment]
Yep. But this didn't work with NativeScript with NativeScript 3. Almost done updating this repo.
