### ISSUE TITLE
Update to tns version 3.0.0 causes blank screen 

### ISSUE THREAD

**Issue by ghost** [EddyVerbruggen/nativescript-bluetooth-demo#17]
JavaScript stack trace:
1   createRootView@file:///app/tns_modules/tns-core-modules/application/application.js:196:75
2   didFinishLaunchingWithOptions@file:///app/tns_modules/tns-core-modules/application/application.js:117:38
3   @[native code]
4   onReceive@file:///app/tns_modules/tns-core-modules/application/application.js:51:32
5   UIApplicationMain@[native code]
6   start@file:///app/tns_modules/tns-core-modules/application/application.js:211:26
7   anonymous@file:///app/app.js:4:18
8   evaluate@[native code]
9   moduleEvaluation@[native code]
10  @[native code]
11  promiseReactionJob@[native code]
JavaScript error:
2017-05-27 06:03:17.260912+0200 Bluetooth[1574:416230] file:///app/tns_modules/tns-core-modules/application/application.js:196:75: JS ERROR Error: A Frame must be used to navigate to a Page.

file:///app/tns_modules/tns-core-modules/application/application.js:196:75: JS ERROR Error: A Frame must be used to navigate to a Page.

**Comment by EddyVerbruggen** [comment]
Thanks for reporting this. I kinda missed this issue.

I was just adding a few updates to the bluetooth plugin and noticed this myself. Almost done repairing it. Closing in advance.
