### ISSUE TITLE
Android: Error in Bluetooth.startScanning: ReferenceError: argkeyMatchNum is not defined

### ISSUE THREAD

**Issue by lhitc** [EddyVerbruggen/nativescript-bluetooth-demo#3]
Happens when tapping "Any Device" in the demo app.
Probably a missing dot in bluetooth.android.js; line 340 should be:

var matchNum = **arg.keyMatchNum** || .....

**Comment by EddyVerbruggen** [comment]
Argh, thanks - fixed.
