### ISSUE TITLE
Android: Coarse location permission has not been granted

### ISSUE THREAD

**Issue by lhitc** [EddyVerbruggen/nativescript-bluetooth-demo#6]
When tapping either scan button after location permission has been granted, console log says "Coarse location permission has not been granted; scanning for devices may fail."

**Comment by EddyVerbruggen** [comment]
Hey Stefan, just to make sure: are you testing the demo app or the plugin? (fine with both btw)

**Comment by EddyVerbruggen** [comment]
Fixed, thanks.

**Comment by lhitc** [comment]
I'm intending to test the plugin, but I consider playing around with the demo app as the first step, especially since we're not having any documentation yet.
And, well, if the demo app doesn't work as expected, or triggers an error in the plugin, I tend to report such issues ;-)

**Comment by EddyVerbruggen** [comment]
Keep it up, much appreciated!
