### ISSUE TITLE
Module or at least demo app should check whether BT is enabled before scanning

### ISSUE THREAD

**Issue by lhitc** [EddyVerbruggen/nativescript-bluetooth-demo#8]
When BT is disabled and I start any scan actions (including "stopScan") I get a "Whoops" dialog and console log says "Error in Bluetooth.startScanning: TypeError: Cannot read property 'startScan' of null".
There should be a check at least in the demo app (if this is to show how to implement BT in a clean way). A more clear error message from the module would be on my wishlist.

**Comment by EddyVerbruggen** [comment]
Agreed, the plugin should do that. And it already did on iOS, but now also on Android (you need to update the plugin to get this change).
